### ISSUE TITLE
Wonder more about your feature extraction.

### ISSUE THREAD

**Issue by liquorleaf** [Gatsby23/360-VIO#2]
Hi!

I read the paper on IEEE ieeexplore. The paper mentioned that "Considering the efficiency, we extract the GFTT features [39] on the equirectangular image. As the aforementioned 360° camera model, the pixels on the u-axis are stretched due to the equirectangular projection."

Does that mean you use a stretched area (for example, an elliptic but not a circle) to compute GFTT corner points?
Or you just perform directly some methods like cv::goodFeatureToTrack() and use a stretched area (rectangular but not square) to perform LK tracking?
Which one did you actually use? Or neither is correct?

Thanks!

**Comment by Gatsby23** [comment]
> Hi!
> 
> I read the paper on IEEE ieeexplore. The paper mentioned that "Considering the efficiency, we extract the GFTT features [39] on the equirectangular image. As the aforementioned 360° camera model, the pixels on the u-axis are stretched due to the equirectangular projection."
> 
> Does that mean you use a stretched area (for example, an elliptic but not a circle) to compute GFTT corner points? Or you just perform directly some methods like cv::goodFeatureToTrack() and use a stretched area (rectangular but not square) to perform LK tracking? Which one did you actually use? Or neither is correct?
> 
> Thanks!

Dear researcher, I just use the goodFeatureToTrack to compute the streched area.

**Comment by Gatsby23** [comment]
> > > Hi!
> > > I read the paper on IEEE ieeexplore. The paper mentioned that "Considering the efficiency, we extract the GFTT features [39] on the equirectangular image. As the aforementioned 360° camera model, the pixels on the u-axis are stretched due to the equirectangular projection."
> > > Does that mean you use a stretched area (for example, an elliptic but not a circle) to compute GFTT corner points? Or you just perform directly some methods like cv::goodFeatureToTrack() and use a stretched area (rectangular but not square) to perform LK tracking? Which one did you actually use? Or neither is correct?
> > > Thanks!
> > 
> > 
> > Dear researcher, I just use the goodFeatureToTrack to compute the streched area.
> 
> Understood! Thanks for your reply, and looking forward to the code!

Happy for solved your question. I'm really sorry I haven't released yet because of my heavy graduation work
