### ISSUE TITLE
when open source？

### ISSUE THREAD

**Issue by zzw1018** [Gatsby23/360-VIO#3]
IEEE TRANSACTIONS ON INDUSTRIAL ELECTRONICS

**Comment by Gatsby23** [comment]
Dear researcher:
Thank you for your interest in this job, and I apologize for delaying the open-source time. Lately, I've been struggling with my thesis. I'll address this matter after completing my thesis, which I expect to be no later than September this year.
Yours

**Comment by minhlenhat21** [comment]
it 4th sep, and i'm looking forward for the source code
